test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.be61e229f9bd7d08d3646fa63eaf6e4573344afa.name = "1.9.3~ynh1"
